const questions = [
    {
      ask: "What is the plural form of 'child'?",
      opt1: "childs",
      opt2: "child",
      opt3: "children",
      answer: "children",
    },
    {
      ask: "Which word means the opposite of 'begin'?",
      opt1: "end",
      opt2: "start",
      opt3: "commence",
      answer: "end",
    },
    {
      ask: "What is the correct spelling?",
      opt1: "recieve",
      opt2: "receive",
      opt3: "recievee",
      answer: "receive",
    },
    {
      ask: "Choose the correct sentence:",
      opt1: "They is going to the party.",
      opt2: "They are going to the party.",
      opt3: "They am going to the party.",
      answer: "They are going to the party.",
    },
    {
      ask: "What part of speech is the word 'quickly'?",
      opt1: "verb",
      opt2: "adjective",
      opt3: "adverb",
      answer: "adverb",
    },
    {
      ask: "Which sentence is grammatically correct?_",
      opt1: "He don't like pizza.",
      opt2: "He doesn't likes pizza.",
      opt3: "He doesn't like pizza.",
      answer: "He doesn't like pizza.",
    },
    {
      ask: "Identify the noun in the sentence: 'The cat chased the mouse.'",
      opt1: "chased",
      opt2: "cat",
      opt3: "mouse",
      answer: "cat",
    },
    {
      ask: "What is the past tense of 'eat'?",
      opt1: "eating",
      opt2: "ate",
      opt3: "eaten",
      answer: "ate",
    },
    {
      ask: "Which sentence uses the correct form of the comparative adjective?",
      opt1: "She runs more faster than me.",
      opt2: "She runs most fast than me.",
      opt3: "She runs faster than me.",
      answer: "She runs faster than me.",
    },
    {
      ask: "What is a synonym for 'happy'?",
      opt1: "sad",
      opt2: "joyful",
      opt3: "angry",
      answer: "joyful",
    },
    {
      ask: "Choose the correct homophone:",
      opt1: "their",
      opt2: "there",
      opt3: "they're",
      answer: "there",
    },
    {
      ask: "What does the prefix 'un-' usually mean?",
      opt1: "not",
      opt2: "opposite of",
      opt3: "too much",
      answer: "not",
    },
    {
      ask: "Identify the subject in the sentence: 'The flowers bloomed beautifully in the garden.'",
      opt1: "flowers",
      opt2: "bloomed",
      opt3: "garden",
      answer: "flowers",
    },
    {
      ask: "What is the plural of 'knife'?",
      opt1: "knifes",
      opt2: "knive",
      opt3: "knives",
      answer: "knives",
    },
    {
      ask: "Which sentence is punctuated correctly?",
      opt1: "I went to the store and bought apples, oranges, bananas, and grapes.",
      opt2: "I went to the store and bought apples, oranges, bananas and grapes.",
      opt3: "I went to the store, and bought apples, oranges, bananas, and grapes.",
      answer:
        "I went to the store and bought apples, oranges, bananas, and grapes.",
    },
    {
      ask: "What is the comparative form of 'bad'?",
      opt1: "badder",
      opt2: "worst",
      opt3: "worse",
      answer: "worse",
    },
    {
      ask: "Which sentence is in the passive voice?",
      opt1: "The cat chased the mouse.",
      opt2: "The mouse was chased by the cat.",
      opt3: "The mouse chased the cat.",
      answer: "The mouse was chased by the cat.",
    },
    {
      ask: "Identify the verb in the sentence: 'She dances gracefully.'",
      opt1: "she",
      opt2: "dances",
      opt3: "gracefully",
      answer: "dances",
    },
    {
      ask: "What is a synonym for 'big'?",
      opt1: "large",
      opt2: "small",
      opt3: "tiny",
      answer: "large",
    },
    {
      ask: "Which word is a conjunction?",
      opt1: "and",
      opt2: "happy",
      opt3: "quickly",
      answer: "and",
    },
    {
      ask: "What is the plural of 'goose'?",
      opt1: "gooses",
      opt2: "geese",
      opt3: "goose",
      answer: "geese",
    },
    {
      ask: "What is the superlative form of 'good'?",
      opt1: "goodest",
      opt2: "better",
      opt3: "best",
      answer: "best",
    },
    {
      ask: "Choose the correct possessive pronoun:",
      opt1: "his",
      opt2: "he's",
      opt3: "its",
      answer: "his",
    },
    {
      ask: "Which sentence is grammatically correct?",
      opt1: "I seen that movie before.",
      opt2: "I saw that movie before.",
      opt3: "I seed that movie before.",
      answer: "I saw that movie before.",
    },
    {
      ask: "What does the suffix '-less' usually mean?",
      opt1: "full of",
      opt2: "without",
      opt3: "more",
      answer: "without",
    },
    {
      ask: "What is the past participle of 'write'?",
      opt1: "wrote",
      opt2: "written",
      opt3: "writing",
      answer: "written",
    },
    {
      ask: "Identify the adverb in the sentence: 'He speaks softly.'",
      opt1: "speaks",
      opt2: "he",
      opt3: "softly",
      answer: "softly",
    },
    {
      ask: "Which word is a preposition?",
      opt1: "with",
      opt2: "walk",
      opt3: "happy",
      answer: "with",
    },
    {
      ask: "What is the comparative form of 'far'?",
      opt1: "farer",
      opt2: "further",
      opt3: "farther",
      answer: "farther",
    },
    {
      ask: "Choose the correct indefinite article:",
      opt1: "a/an",
      opt2: "an",
      opt3: "the",
      answer: "a/an",
    },
  ];
  export default  questions